name: build and test main branch
on:
  push:
    branches:
      - main
jobs:
  build_and_test:
    name: Checkout code, build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: |
          zig build
      - name: Test
        run: |
          zig build test